FROM ruby:2.4.2

RUN apt-get update -qq \
  && apt-get install -y \
    build-essential \
    ruby-dev \
    zlib1g-dev \
    liblzma-dev \
    libxslt-dev \
    libxml2-dev \
    locales \
    libpq-dev \
    postgresql-client-common \
    postgresql-client

RUN curl -sL https://deb.nodesource.com/setup_8.x | bash -
RUN apt-get install -y nodejs

RUN npm install -g webpack

